import { afterAll, beforeAll, describe, expect, it } from "vitest";

try {
  process.loadEnvFile(".env.local");
} catch {
  // CI can provide DATABASE_URL directly.
}

import { AI_GATEWAY_CANONICAL_PROMPT_VERSION } from "./gateway";
import { generateAiCanonicalWikiPageRevision } from "./wiki-canonical";
import type { WikiActor } from "@/src/auth/wiki-auth";
import { getDb } from "@/src/db/client";
import {
  getPublishedWikiPageBySlug,
  getWikiPageSnapshot,
  saveWikiPageWithRevision,
  type WikiPageRevisionAiProvenance,
  type WikiTenant,
} from "@/src/db/wiki";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is required for AI canonical wiki tests.");
}

describe.sequential("AI canonical wiki page generation", () => {
  let db: ReturnType<typeof getDb>;
  const runId = `ai_canonical_test_${Date.now()}_${Math.random()
    .toString(36)
    .slice(2)}`;
  const gameId = `${runId}_game`;
  const tenantId = `${runId}_tenant`;
  const tenantSlug = runId.replaceAll("_", "-");
  const tenant: WikiTenant = {
    id: tenantId,
    slug: tenantSlug,
    name: "AI Canonical Test Wiki",
    gameSlug: `${tenantSlug}-game`,
    gameTitle: "Marathon",
  };
  const actor: WikiActor = {
    id: "editor-canonical-1",
    email: "canonical-editor@example.com",
    name: "Canonical Editor",
    provider: "dev",
  };

  beforeAll(async () => {
    db = getDb();

    await db
      .insertInto("games")
      .values({
        id: gameId,
        slug: tenant.gameSlug,
        title: tenant.gameTitle,
        franchise: "Marathon",
        developer: null,
        publisher: null,
        release_date: null,
        metadata: null,
      })
      .execute();

    await db
      .insertInto("tenants")
      .values({
        id: tenantId,
        game_id: gameId,
        slug: tenantSlug,
        name: tenant.name,
        status: "active",
        primary_locale: "en",
      })
      .execute();

    await db
      .insertInto("wiki_sources")
      .values([
        {
          id: `${runId}_source_overrun`,
          tenant_id: tenantId,
          page_id: null,
          revision_id: null,
          source_key: "overrun-ar",
          source_type: "seed_context",
          title: "Overrun AR test source context",
          url: null,
          publisher: "Test seed corpus",
          context_text:
            "Overrun AR seeded context for an automatic-rifle style Marathon equipment article.",
          topic_slugs: ["overrun-ar", "weapons", "equipment"],
          retrieved_at: null,
          metadata: { test: true },
        },
        {
          id: `${runId}_source_unrelated`,
          tenant_id: tenantId,
          page_id: null,
          revision_id: null,
          source_key: "unrelated-faction",
          source_type: "seed_context",
          title: "Unrelated faction context",
          url: null,
          publisher: "Test seed corpus",
          context_text: "This unrelated faction context must not be retrieved.",
          topic_slugs: ["factions"],
          retrieved_at: null,
          metadata: { test: true },
        },
      ])
      .execute();
  });

  afterAll(async () => {
    await db.deleteFrom("tenants").where("id", "=", tenantId).execute();
    await db.deleteFrom("games").where("id", "=", gameId).execute();
    await db.destroy();
  });

  it("publishes a new AI canonical page revision with retrieved source provenance", async () => {
    const result = await generateAiCanonicalWikiPageRevision(
      {
        tenant,
        actor,
        pageTitle: "Overrun AR",
        targetSlug: "Overrun AR",
        sourceContext: "Editor notes identify this as a weapon topic.",
        refreshReason: "new_page",
      },
      {
        db,
        generateCanonicalPage: async (request) => {
          expect(request.existingPage).toBeNull();
          expect(request.targetSlug).toBe("overrun-ar");
          expect(request.sourceContext).toContain(
            "Overrun AR seeded context",
          );
          expect(request.sourceContext).not.toContain(
            "unrelated faction context",
          );

          return {
            title: "Overrun AR",
            summary: "AI canonical overview of the weapon topic.",
            bodyMarkdown:
              "## Overview\n\nOverrun AR is covered as the canonical public wiki article generated by AI from stored source context.",
            sourceContextSummary:
              "Used editor context and retrieved Overrun AR seed context.",
            provider: "vercel-ai-gateway",
            model: "xai/grok-test",
            responseId: "gateway_resp_canonical_new",
            promptVersion: AI_GATEWAY_CANONICAL_PROMPT_VERSION,
          };
        },
      },
    );

    const revision = await db
      .selectFrom("wiki_page_revisions")
      .select([
        "revision_number",
        "change_note",
        "ai_provenance as aiProvenance",
      ])
      .where("tenant_id", "=", tenantId)
      .where("page_id", "=", result.page.id)
      .executeTakeFirstOrThrow();
    const provenance = revision.aiProvenance as WikiPageRevisionAiProvenance;

    expect(result.page).toMatchObject({
      slug: "overrun-ar",
      title: "Overrun AR",
      status: "published",
      latestRevisionNumber: 1,
      bodyMarkdown:
        "## Overview\n\nOverrun AR is covered as the canonical public wiki article generated by AI from stored source context.",
      sources: [
        expect.objectContaining({
          sourceKey: "overrun-ar",
          title: "Overrun AR test source context",
        }),
      ],
    });
    expect(revision).toMatchObject({
      revision_number: 1,
      change_note: "AI canonical generation: new_page",
    });
    expect(provenance).toMatchObject({
      provider: "vercel-ai-gateway",
      modelId: "xai/grok-test",
      promptVersion: AI_GATEWAY_CANONICAL_PROMPT_VERSION,
      responseId: "gateway_resp_canonical_new",
      sourceContextSummary:
        "Used editor context and retrieved Overrun AR seed context.",
      sourceReferences: [
        expect.objectContaining({
          sourceKey: "overrun-ar",
          title: "Overrun AR test source context",
        }),
      ],
      refreshReason: "new_page",
      requestedBy: actor.id,
    });
    expect(new Date(provenance.generatedAt).getTime()).not.toBeNaN();
    await expect(
      getPublishedWikiPageBySlug(tenantId, "overrun-ar", db),
    ).resolves.toMatchObject({
      bodyMarkdown:
        "## Overview\n\nOverrun AR is covered as the canonical public wiki article generated by AI from stored source context.",
    });
  });

  it("refreshes an existing page through normal revision history", async () => {
    const page = await saveWikiPageWithRevision(
      {
        tenantId,
        slug: "weapons",
        title: "Weapons",
        summary: "Initial weapons summary",
        bodyMarkdown: "## Weapons\n\nInitial weapons body.",
        status: "published",
        actorId: "seed-editor",
      },
      db,
    );

    await generateAiCanonicalWikiPageRevision(
      {
        tenant,
        actor,
        pageTitle: "Weapons",
        targetSlug: "weapons",
        sourceContext: "Refresh from the latest official weapon overview.",
        refreshReason: "source_update",
      },
      {
        db,
        generateCanonicalPage: async (request) => {
          expect(request.existingPage?.latestRevisionNumber).toBe(1);
          expect(request.existingPage?.bodyMarkdown).toContain("Initial weapons");

          return {
            title: "Weapons",
            summary: "AI-refreshed canonical weapons summary.",
            bodyMarkdown:
              "## Weapons\n\nAI refreshed the public canonical weapons article through the revision path.",
            sourceContextSummary:
              "Used the prior revision and latest official weapon overview.",
            provider: "vercel-ai-gateway",
            model: "openai/gpt-5-nano",
            responseId: null,
            promptVersion: AI_GATEWAY_CANONICAL_PROMPT_VERSION,
          };
        },
      },
    );

    const revisions = await db
      .selectFrom("wiki_page_revisions")
      .select([
        "revision_number",
        "body_markdown as bodyMarkdown",
        "ai_provenance as aiProvenance",
      ])
      .where("tenant_id", "=", tenantId)
      .where("page_id", "=", page.id)
      .orderBy("revision_number", "asc")
      .execute();

    expect(revisions).toHaveLength(2);
    expect(revisions[0]).toMatchObject({
      revision_number: 1,
      aiProvenance: null,
    });
    expect(revisions[1]).toMatchObject({
      revision_number: 2,
      bodyMarkdown:
        "## Weapons\n\nAI refreshed the public canonical weapons article through the revision path.",
    });
    expect(
      revisions[1]?.aiProvenance as WikiPageRevisionAiProvenance,
    ).toMatchObject({
      modelId: "openai/gpt-5-nano",
      refreshReason: "source_update",
      sourceContextSummary:
        "Used the prior revision and latest official weapon overview.",
    });
  });

  it("does not mutate existing public reads when AI Gateway is unavailable", async () => {
    const page = await saveWikiPageWithRevision(
      {
        tenantId,
        slug: "stable-public-page",
        title: "Stable Public Page",
        summary: "Stable summary",
        bodyMarkdown: "## Stable\n\nThis public page is already published.",
        status: "published",
        actorId: "seed-editor",
      },
      db,
    );

    await expect(
      generateAiCanonicalWikiPageRevision(
        {
          tenant,
          actor,
          pageTitle: "Stable Public Page",
          targetSlug: "stable-public-page",
          refreshReason: "manual_refresh",
        },
        {
          db,
          env: {},
        },
      ),
    ).rejects.toThrow("AI Gateway is not configured");

    const publicPage = await getWikiPageSnapshot(
      tenantSlug,
      "stable-public-page",
      db,
    );
    const revisionCount = await db
      .selectFrom("wiki_page_revisions")
      .select(({ fn }) => fn.countAll<number>().as("count"))
      .where("tenant_id", "=", tenantId)
      .where("page_id", "=", page.id)
      .executeTakeFirstOrThrow();

    expect(publicPage?.page).toMatchObject({
      slug: "stable-public-page",
      title: "Stable Public Page",
      bodyMarkdown: "## Stable\n\nThis public page is already published.",
      latestRevisionNumber: 1,
    });
    expect(Number(revisionCount.count)).toBe(1);
  });

  it("handles missing stored context without blocking canonical generation", async () => {
    const result = await generateAiCanonicalWikiPageRevision(
      {
        tenant,
        actor,
        pageTitle: "No Context Topic",
        targetSlug: "no-context-topic",
        refreshReason: "new_page",
      },
      {
        db,
        generateCanonicalPage: async (request) => {
          expect(request.sourceContext).toBeNull();

          return {
            title: "No Context Topic",
            summary: "Generated without stored context.",
            bodyMarkdown:
              "## Overview\n\nThis canonical page was generated without matching stored context.",
            sourceContextSummary: "No stored source context matched this topic.",
            provider: "vercel-ai-gateway",
            model: "openai/gpt-5-nano",
            responseId: "gateway_resp_no_context",
            promptVersion: AI_GATEWAY_CANONICAL_PROMPT_VERSION,
          };
        },
      },
    );

    expect(result.page).toMatchObject({
      slug: "no-context-topic",
      latestRevisionNumber: 1,
      sources: [],
    });
    expect(result.provenance).toMatchObject({
      sourceReferences: [],
      sourceContextSummary: "No stored source context matched this topic.",
    });
  });
});
